import{a as p,S as y,i as c}from"./assets/vendor-b11e2a50.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function m(s,e){const o="https://pixabay.com/api/",l=new URLSearchParams({key:"44175517-753270956c641713e32eb091d",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:15}),t=`${o}?${l}`;return(await p(t)).data}function g(s){return s.map(e=>`<li class="gallery-item">
  <a class="gallery-link" href="${e.largeImageURL}">
    <img
      class="gallery-image"
      src="${e.webformatURL}"
      alt="${e.tags}"
    />
    <ul class="image-info">
    <li class="info-item"><div class="item-text">Likes</div><div class="item-value">${e.likes}</div></li>
    <li class="info-item"><div class="item-text">Views</div><div class="item-value">${e.views}</div></li>
    <li class="info-item"><div class="item-text">Comments</div><div class="item-value">${e.comments}</div></li>
    <li class="info-item"><div class="item-text">Downloads</div><div class="item-value">${e.downloads}</div></li>
    </ul>
  </a>
</li>`).join("")}const v=document.querySelector(".form"),f=document.querySelector(".gallery"),u=document.querySelector(".loader"),i=document.querySelector(".load-more-btn"),h=new y(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});let n=null,a=null;v.addEventListener("submit",b);function b(s){s.preventDefault(),a=1,n=s.target.elements.search.value.trim(),n!==""&&(s.target.reset(),u.classList.remove("is-hiding"),m(n,a).then(e=>{e.total===0&&c.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"topRight"});const o=g(e.hits);f.innerHTML=o,h.refresh()}).catch(e=>{c.show({message:"Internal server error!",messageColor:"white",backgroundColor:"red",position:"topRight"})}).finally(()=>{u.classList.add("is-hiding"),i.classList.remove("is-hiding")}))}i.addEventListener("click",L);async function L(){a+=1,i.disabled=!0;try{const s=await m(n,a);f.insertAdjacentHTML("beforeend",g(s.hits)),h.refresh(),a>=34&&(i.classList.add("is-hiding"),c.show({message:"We are sorry, but you've reached the end of search results.",messageColor:"black",backgroundColor:"lightblue",position:"topRight"}));const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"})}catch{c.show({message:"Internal server error!",messageColor:"white",backgroundColor:"red",position:"topRight"})}finally{i.disabled=!1}}
//# sourceMappingURL=commonHelpers.js.map
